# -*- coding: utf-8 -*-
"""DashVacina.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1L0VBiALVl_gFx7Ux0_AC_ejLmPx39XFJ
"""

import pandas as pd

import streamlit as st

df = pd.read_csv('vacinacao - vacinacao.csv')

df['date'] = pd.to_datetime(df['date'])

df['location'] = df['location'].str.upper()

df_serie_temporal = df[['date', 'location', 'total_vaccinations']].dropna()

paises_alvo = ['BRAZIL', 'INDIA', 'UNITED STATES']
df_diario_paises = df[df['location'].isin(paises_alvo)]

df_pizza_total = df_diario_paises.groupby('location')['people_fully_vaccinated'].max().reset_index()

st.subheader("Total de Vacinações por Data e Países")

df_pivot_serie = df_serie_temporal.pivot(index='date', columns='location', values='total_vaccinations')
st.line_chart(df_pivot_serie)

import plotly.express as px

st.subheader("Pessoas Diariamente Vacinadas (BRA, IND, USA)")

fig_hist = px.histogram(df_diario_paises,
                        x="date",
                        y="daily_vaccinations",
                        color="location",
                        barmode="group",
                        title="Vacinação Diária")
st.plotly_chart(fig_hist)

st.subheader("Distribuição de Pessoas Totalmente Vacinadas")
fig_pizza = px.pie(df_pizza_total,
                   values='people_fully_vaccinated',
                   names='location',
                   title='Total de Vacinados por País')
st.plotly_chart(fig_pizza)
